require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

pod 'GoogleMaps'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'RNFS', :path => '../node_modules/react-native-fs'
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path

target 'IMATeam' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



 # pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

  
  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'
#required for file system
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'
  target 'IMATeamTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    ################### ADD THE FOLLOWING #########################
    installer.pods_project.targets.each do |target|
          if target.name == "React-Core.common-AccessibilityResources"
            target.remove_from_project
          end
        end
    ###############################################################
  end
end
